name: Email sending
on: workflow_dispatch
jobs:
  artifact-generation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shop: [es, de ,be]
    steps:
      - name: Generate dummy reports
        run: |
          mkdir -p ./reports/html
          echo "<p>hola</p>" > ./reports/html/index.html
          echo "{}" > ./reports/report.json
      - name: Full report artifact
        uses: actions/upload-artifact@v3
        with:
          name: full-report-${{ matrix.shop }}.zip
          path: ./reports/
      - name: Email report artifact
        uses: actions/upload-artifact@v3
        with:
          name: email-report-${{ matrix.shop }}.zip
          path: ./reports/html/
  email-send:
    runs-on: ubuntu-latest
    needs: artifact-generation
    steps:
      - name: Recover artifacts
        uses: actions/download-artifact@v3
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Execution report summary
          to: miguelangel.santamaria@izertis.com
          from: Github actions
          body: Execution summary of ${{github.repository}}
          attachments: ./email-report-es.zip
