name: Email sending
on: workflow_dispatch
jobs:
  create-testbed:
    runs-on: ubuntu-latest
    outputs:
      report-recipients: ${{ steps.emails.outputs.recipients }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Recover email list
        id: emails
        run: |
          RECIPIENTS=$(cat ${GITHUB_WORKSPACE}/.github/workflows/data/report_emails.txt)
          echo "::notice title=Email recipients for html reports::${RECIPIENTS}"
          echo "::set-output name=recipients::${RECIPIENTS}"
  artifact-generation:
    runs-on: ubuntu-latest
    needs: create-testbed
    strategy:
      matrix:
        shop: [es, de ,be]
    steps:
      - name: Generate dummy reports
        run: |
          mkdir -p ./reports/html
          echo "<p>hola</p>" > ./reports/html/index.html
          echo "{}" > ./reports/report.json
      - name: Full report artifact
        uses: actions/upload-artifact@v3
        with:
          name: full-report-${{ matrix.shop }}.zip
          path: ./reports/
      - name: Email report artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-report-${{ matrix.shop }}
          path: ./reports/html/
  email-send:
    runs-on: ubuntu-latest
    needs: [create-testbed, artifact-generation]
    steps:
      - name: Recover artifacts
        uses: actions/download-artifact@v3
      - name: Display structure of downloaded artifacts
        run: ls -R
      - name: Build final email report
        run: zip reports.zip -r html-report-*
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Execution report summary
          to: ${{ needs.create-testbed.outputs.report-recipients }}
          from: Github actions
          body: Execution reports of ${{github.repository}}
          attachments: reports.zip
