name: Read data from JSON file
on: workflow_dispatch
jobs:
  read-file:
    runs-on: ubuntu-latest
    outputs:
      data: ${{ steps.read-json.outputs.data }}
    steps:
      - uses: actions/checkout@v2
      - name: Read JSON file
        id: read-json
        run: |
          JSON=$(cat ${GITHUB_WORKSPACE}/.github/workflows/data/stores.json)
          # the following lines are only required for multi line json
          JSON="${JSON//'%'/'%25'}"
          JSON="${JSON//$'\n'/'%0A'}"
          JSON="${JSON//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=data::${JSON}"
  print-data:
    runs-on: ubuntu-latest
    needs: read-file
    steps:
      - name: Print readed data
        run: |
          echo ${{fromJson(needs.read-file.outputs.data)}}
