name: Reusable workflow
on:
  workflow_call:
    inputs:
      mobile_platform:
        description: 'The platform to test'
        required: true
        type: string
      test_branch:
        description: 'The branch to test'
        default: 'master'
        required: false
        type: string
      tags:
        description: "Cucumber tags"
        default: ''
        required: false
        type: string
    secrets:
      token:
        required: true
jobs:
  print-inputs:
    runs-on: ubuntu-latest

    steps:
      - name: Print the inputs to STDOUT
        run: |
          echo The mobile_platform is ${{ inputs.mobile_platform }}
          echo The test_branch is ${{ inputs.test_branch }}
          echo The tags are ${{ inputs.tags }}
          echo The token is ${{ secrets.token }}
          echo The Action Path is ${GITHUB_WORKSPACE}
