name: TEST parameters
on: workflow_dispatch
jobs:
  runs-on: ubuntu-latest
  call-reusable-workflow:
    uses: miguelas-itx/actions-playground/.github/workflows/reusable-workflow.yml@main
    with:
      mobile_platform: android
      tags: '@TAG'
    secrets:
      token: 'a secret'
  show-repo-info:
    steps:
      - name: Show env info
        run: |
          echo ${GITHUB_ACTION_PATH}
          echo ${GITHUB_REPOSITORY}
