name: TEST parameters
on: workflow_dispatch
jobs:
  call-reusable-workflow:
    uses: miguelas-itx/actions-playground/.github/workflows/reusable-workflow.yml@main
    with:
      mobile_platform: android
      tags: '@TAG'
    secrets:
      token: 'a secret'
  show-repo-info:
    runs-on: ubuntu-latest
    steps:
      - name: Show env info
        run: |
          echo "Action path: ${GITHUB_ACTION_PATH}"
          echo "Repository: ${GITHUB_REPOSITORY}"
          echo ${{ env.GITHUB_ACTION_PATH }}
          echo ${{ env.GITHUB_REPOSITORY }}
